### ISSUE TITLE
Not seeing any output if Rails log level is not :debug

### ISSUE THREAD

**Issue by dechimp** [AndyObtiva/puts_debuggerer#20]
Any log level below :debug doesn't seem to show any pd output (Rails 6.1 + ruby 2.7.4). It's not really what I expect since `puts` appears in any log level.

**Comment by AndyObtiva** [comment]
I didn't think there is even a log level below `:debug`. 

This Rails webpage lists the following debug levels: 

> The available log levels are: :debug, :info, :warn, :error, :fatal, and :unknown, corresponding to the log level numbers from 0 up to 5, respectively. 

https://guides.rubyonrails.org/debugging_rails_applications.html

So, I am not sure if you are even setting a proper log level to begin with.

What does your `Rails.logger.level` return in `rails console`?

BTW, this is configurable regardless via `PutsDebuggerer.printer`.

By default, it has this value:

```ruby
PRINTER_RAILS = lambda do |output|
  puts output if Rails.env.test?
  Rails.logger.debug(output)
end
```

You can set `PutsDebuggerer.printer` to any lambda/proc you want (usually in a Rails initializer like `config/initializers/puts_debuggerer_options.rb`). 

For example:

```ruby
PutsDebuggerer.printer = lambda do |output| 
  puts output if Rails.env.test?
  Rails.logger.error(output)  
end
```

Now, Rails pd printouts happen as error logs, meaning at the level of error, which is usually guaranteed to show up though, `warn(output)` might be a less extreme more practical alternative.

**Comment by dechimp** [comment]
Sorry, in my mind "below" and "above" are probably backwards when it comes to log levels.

I have my log level set to `info` in one of the apps I'm working on, so I was confused as to why `pd` wasn't working at all.

I mainly made this issue because I know someone else is going to run into this same thing.  Thanks for providing the setup code needed to make pd more agnostic to log levels.

**Comment by AndyObtiva** [comment]
Fair enough. I just added the clarification above to the project README under Instructions:
https://github.com/AndyObtiva/puts_debuggerer/blob/master/README.md#option-1-bundler

I am closing this issue as such. 

Cheers.
