### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by konung** [AndyObtiva/puts_debuggerer#21]
Jut an FYI

I just tried puts_debugger in a legacy project I have that runs Ruby 2.3.8 🧟‍♂️ in a container, and it works! 😀

Thank you

Very helpful!

<img width="1036" alt="image" src="https://github.com/AndyObtiva/puts_debuggerer/assets/72493/b3a79c9a-59fd-4496-90aa-26806189c9d4">

**Comment by AndyObtiva** [comment]
You’re welcome.
